### ISSUE TITLE
register a user

### ISSUE THREAD

**Issue by annaship** [avoorhis/vamps-node.js#19]
Successfully created a new user on one laptop, but not on my office machine:

GET /users/signup 200 44.273 ms - -

INSERT INTO user (username, encrypted_password, first_name, last_name, email, institution, active, sign_in_count, current_sign_in_at,last_sign_in_at) VALUES ('AnnaSh', 'yFSUVr+NupF9DO3SYKFkzg==', 'Anna', 'Shipunova', 'ashipunova@mbl.edu', 'MBL', 1, 1, CURRENT_TIMESTAMP(),  '' )

/Users/ashipunova/BPC/vamps-node.js/config/passport.js:198
                    newUserMysql.user_id = rows.insertId;
                                               ^
TypeError: Cannot read property 'insertId' of undefined
    at Query.<anonymous> (/Users/ashipunova/BPC/vamps-node.js/config/passport.js:198:48)
    at Query.onResult (/Users/ashipunova/BPC/vamps-node.js/node_modules/mysql2/lib/pool.js:133:10)
    at Query.Command.execute (/Users/ashipunova/BPC/vamps-node.js/node_modules/mysql2/lib/commands/command.js:27:12)
    at PoolConnection.Connection.handlePacket (/Users/ashipunova/BPC/vamps-node.js/node_modules/mysql2/lib/connection.js:310:28)
    at PacketParser.onPacket (/Users/ashipunova/BPC/vamps-node.js/node_modules/mysql2/lib/connection.js:83:65)
    at PacketParser.executeStart (/Users/ashipunova/BPC/vamps-node.js/node_modules/mysql2/lib/packet_parser.js:39:12)
    at Socket.<anonymous> (/Users/ashipunova/BPC/vamps-node.js/node_modules/mysql2/lib/connection.js:95:31)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)

**Comment by annaship** [comment]
fixed
